PREFIX=/usr/local
BINDIR=$(PREFIX)/bin
LIBDIR=$(PREFIX)/lib/compcert
ARCH=arm
VARIANT=hardfloat
SYSTEM=linux
AR=arm-linux-gnueabihf-ar
CC=arm-linux-gnueabihf-gcc -mfloat-abi=hard -mfpu=neon -mcpu=cortex-a8
CPREPRO=arm-linux-gnueabihf-gcc -mfloat-abi=hard -mfpu=neon -mcpu=cortex-a8 -U__GNUC__ '-D__REDIRECT(name,proto,alias)=name proto' '-D__REDIRECT_NTH(name,proto,alias)=name proto' -E
CASM=arm-linux-gnueabihf-gcc -mfloat-abi=hard -mfpu=neon -mcpu=cortex-a8 -c
CASMRUNTIME=arm-linux-gnueabihf-gcc -mfloat-abi=hard -mfpu=neon -mcpu=cortex-a8 -fomit-frame-pointer -fPIC -U__GNUC__ -c
CLINKER=arm-linux-gnueabihf-gcc -mfloat-abi=hard -mfpu=neon -mcpu=cortex-a8 -fomit-frame-pointer -fPIC -U__GNUC__
LIBMATH=-lm
HAS_RUNTIME_LIB=true
CCHECKLINK=false
ASM_SUPPORTS_CFI=true
